alter table stats rename to oldtable;
create table stats ("year" int4,
"week" int4,
"name" varchar(30),
"id" int4,
"pass_pts_ppr" float8,
"rush_pts_ppr" float8,
"rec_pts_ppr" float8,
"pass_pts" float8,
"rush_pts" float8,
"rec_pts" float8,
"tot_pts_ppr" float8,
"tot_pts" float8,
"home" varchar(10),
"team" varchar(3),
"pos" varchar(5),
"defense_ast" float8,
"defense_ffum" float8,
"defense_int" float8,
"defense_int_yds" float8,
"defense_qbhit" float8,
"defense_sk" float8,
"defense_tkl" float8,
"defense_tkl_loss" float8,
"first_down" float8,
"fumbles_lost" float8,
"passing_att" float8,
"passing_cmp" float8,
"passing_first_down" float8,
"passing_incmp" float8,
"passing_int" float8,
"passing_tds" float8,
"passing_yds" float8,
"receiving_lng" float8,
"receiving_rec" float8,
"receiving_tar" float8,
"receiving_tds" float8,
"receiving_yac_yds" float8,
"receiving_yds" float8,
"rushing_att" float8,
"rushing_first_down" float8,
"rushing_lng" float8,
"rushing_tds" float8,
"rushing_yds" float8,
"third_down_att" float8,
"third_down_conv" float8,
"third_down_failed" float8);
insert into stats (week, year, name, id, home, team, pos, defense_ast, defense_ffum, defense_int, defense_int_yds, defense_qbhit,
defense_sk, defense_tkl, defense_tkl_loss, first_down, fumbles_lost, passing_att, passing_cmp,
passing_first_down, passing_incmp, passing_int, passing_tds, passing_yds, receiving_lng,
receiving_rec, receiving_tds, receiving_yac_yds, receiving_yds, rushing_att, rushing_first_down,
rushing_lng, rushing_tds, rushing_yds, third_down_att, third_down_conv, third_down_failed) 
select 
week, year, name, id, home, team, pos, defense_ast, defense_ffum, defense_int, defense_int_yds, defense_qbhit,
defense_sk, defense_tkl, defense_tkl_loss, first_down, fumbles_lost, passing_att, passing_cmp,
passing_first_down, passing_incmp, passing_int, passing_tds, passing_yds, receiving_lng,
receiving_rec, receiving_tds, receiving_yac_yds, receiving_yds, rushing_att, rushing_first_down,
rushing_lng, rushing_tds, rushing_yds, third_down_att, third_down_conv, third_down_failed from oldtable;